# Generated by Django 5.0.7 on 2024-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(null=True),
        ),
    ]
